# -*- coding: utf-8 -*-
"""Bulk_Download_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S72APWEYHkowzTFAKcFuml18hTqcENdN
"""

# Dependencies
from google.colab import drive

drive.mount("/content/drive")
import requests
import os
import ipywidgets as widgets
import csv
from IPython.display import display
from datetime import date
import pandas as pd
from tqdm import tqdm


# File Upload Prompt
from google.colab import files

uploaded = files.upload()
csv_name = list(uploaded.keys())[0]


# Get Column Names
column_names = list(pd.read_csv(csv_name).columns)


# Define URL Columns
link_box = widgets.Dropdown(options=column_names, description="URL:", disabled=False)


# Folder Name Box
today = str(date.today())

folder_name_box = widgets.Text(
    value=f"Download-{today}",
    placeholder="Enter Folder Name",
    description="Folder Name:",
    disabled=False,
)


# Columns for Naming
file_name_box = widgets.SelectMultiple(
    options=column_names,
    rows=len(column_names),
    description="File Name:",
    disabled=False,
)


# Insure unique file names
def check_unique(path, file_name_widget, row, url):
    name = "_".join([row[x] for x in file_name_widget.value]) + "." + url.split(".")[-1]
    file_list = os.listdir(path)
    matches = [name == x for x in file_list]
    i = 1
    while matches.count(True) != 0:
        name = (
            "_".join([row[x] for x in file_name_widget.value])
            + f"_{i}"
            + "."
            + url.split(".")[-1]
        )
        i = i + 1
        matches = [name == x for x in file_list]
    return name


# Save Image Function
def save_image(path, file_name_widget, row, url):
    # Make unique file name
    name = check_unique(path, file_name_widget, row, url)

    # Save file
    file_name = f"{path}/{name}"
    img_data = requests.get(url).content
    with open(f"{file_name}", "wb") as handler:
        handler.write(img_data)


# Downloader Function
def csv_bulk_download(b):
    try:
        # Make new folder
        folder_name = folder_name_box.value
        path = f"drive/MyDrive/{folder_name}"
        os.mkdir(path)
    except:
        pass

    # Get URL Columns from Widgets
    url_column = link_box.value

    # Download if url is present
    with open(csv_name, newline="") as csvfile:
        read_csv = csv.DictReader(csvfile, delimiter=",")
        for row in tqdm(read_csv, desc="Working..."):
            if row[url_column] == "":
                pass
            else:
                save_image(path, file_name_box, row, row[url_column])

    print("\n")
    print("Finished!")


# Downloader Button
downloader = widgets.Button(
    description="Download",
    disabled=False,
    button_style="success",
    tooltip="Click to run",
    icon="download",
)


# Display Widgets
print("\n \n Setup \n")
display(link_box)
display(file_name_box)

print("\n \n \n")
print("Output Folder Name")
display(folder_name_box)

print("\n \n \n")
downloader.on_click(csv_bulk_download)
display(downloader)
